
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mooc_mettingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml
